### PR TITLE
Link to the app details page from the widget action menu

### PR DESCRIPTION
**Pull request by apetro**
Especially since the context menu no longer itself includes the app description, link to a page that does.

### CODE REVIEW

**Comment by jordanjones98** [comment]
👍

**Comment by apetro** [comment]
Needs a bit more testing...

**Comment by jordanjones98** [comment]
@apetro does this link exist in the portal?

**Comment by apetro** [comment]
Status quo expanded mode widgets have this link.

Screen Shot 2019-08-26 at 3 11 02 PM

**Comment by jordanjones98** [comment]
If you could figure out how to have it display text that would work too, but it was not behaving well for me. It seems like it isn't very "material" to put text in there.

**Comment by apetro** [comment]
Backed out the attempt to handle missing `uid` that was too clever by half, since it didn't actually work and resulted in action menu not opening.  Failing to provide `uid` is just not allowed, that's what is means for it to be a "required" attribute. :)

**Comment by apetro** [comment]
> If you could figure out how to have it display text that would work too, but it was not behaving well for me. It seems like it isn't very "material" to put text in there.

I think linking the details page is probably a better solution. Those are pages I'd like to raise awareness of anyway since they mean every content item in MyUW has a shareable URL.

**Pull request merged**
